project:
  type: website

website:
  title: "Visualization Project"
  navbar:
    left:
      - href: main.ipynb
        text: Main
      - href: https://github.com/anly501/dsan-5000-project-1152586743
        text: Code
      

format:
  html:
    theme: cosmo
    toc: true



