project:
  type: website
  output-dir: docs


website:
  title: "Visualization Project"
  navbar:
    left:
      - text: Main
        href: main.ipynb
      - text: Code
        href: https://github.com/1152586743/viz_project


format:
  html:
    theme: united
    toc: true


