project:
  type: website

website:
  title: "Visualization Project"
  navbar:
    left:
      - text: Main
        href: main.ipynb
      - text: Code
        href: https://github.com/1152586743/viz_project

output-dir: docs

format:
  html:
    theme: cosmo
    toc: true



